### ISSUE TITLE
Site update screenshots are way too big.

### ISSUE THREAD

**Issue by jackomix** [WheatleyTheCoder/meow#1]
On the comments tab, if you take a look at a "[name] updated their site" post, the screenshot is way to big. Perhaps it could be the code doesn't work around the users monitor?

![image](https://user-images.githubusercontent.com/13090766/29973296-17348e60-8efd-11e7-8286-b46ab11a1e13.png)

**Comment by PitsPower** [comment]
I think it may be to do with the text underneath the image rather than the image itself. I'll see if I can shorten the text if it gets too long.

**Comment by jackomix** [comment]
That's probably what it is...

**Comment by jackomix** [comment]
Yeah, when the text is shorter it looks fine.

**Comment by PitsPower** [comment]
Should be fixed now!
